### ISSUE TITLE
Results without Highlights / Snippets

### ISSUE THREAD

**Issue by anuragji** [scholarslab/SolrSearch#114]
I have a collection of documents, all of which have OCR'd text in the Item Type Metadata field named _Text_, which gets indexed by the SolrSearch plugin. Sometimes when I do a search, I get results which do not have a snippet, even though other items returned in the same query do have a snippet, from the same metadata field.

Has anyone else experienced a similar behavior before?

**Comment by erochest** [comment]
I haven't seen this, but I'll try to reproduce it.

**Comment by anuragji** [comment]
Is there a log file I could check? I checked the query result with a debugger and there where indeed no highlight snippets returned.

**Comment by erochest** [comment]
Not that I can think of.

By the way, what version of Solr are you running? They sometimes change snippets calls, so I'd like to make sure I'm working with the same one.

**Comment by anuragji** [comment]
Solr 4.10.2

The odd thing is that the same query returns both, results with and without snippets.

**Comment by erochest** [comment]
Thanks.

My experience has been that snippets are temperamental.

**Comment by anuragji** [comment]
That makes me feel better ;)

**Comment by erochest** [comment]
@anuragji , I've been trying to replicate this, but I haven't been able to yet. If you have any PDFs that this is happening with, could you email them to me, please? That would be immensely helpful.

(And sorry it's taken me so long to get back to this. I'm hoping to push out a new release of this plugin in this summer.)

**Comment by anuragji** [comment]
I am out of the office this whole week,  but will try to send you a PDF once I get back next week.

Thanks!

**Comment by erochest** [comment]
That sounds great! Thanks

**Comment by anuragji** [comment]
Alas, I checked with the clients, since all the PDFs in question are part of a private collection and they do not want me to forward them to you. I am really sorry that I cannot be of more help.

**Comment by erochest** [comment]
Thanks for checking. I'll poke at it some more.

**Comment by erochest** [comment]
Hopefully your issue was just that the hits weren't close enough to the beginning of the document.

If that's the case, then when this is released, look for the option **Extent of Document Highlightable** on the *Results* configuration tab. Make its value larger.
