### ISSUE TITLE
Display thumbnails in search results?

### ISSUE THREAD

**Issue by lydiatsai** [scholarslab/SolrSearch#116]
Can search results show thumbnails for items? I am not sure how to implement this feature if so. Perhaps I am missing something major?

**Comment by erochest** [comment]
Thumbnails for images should show in the search results. (See the screenshot.) Is this what you're trying to do?

![screen shot 2015-01-28 at 3 44 17 pm](https://cloud.githubusercontent.com/assets/43783/5946558/aabac0fc-a704-11e4-8619-b0ad836cb718.png)

**Comment by lydiatsai** [comment]
Hi erochest, I think there might be something wrong with my installation? I am seeing this:

![seneca omeka solr search](https://cloud.githubusercontent.com/assets/3915858/6129034/29a0223c-b109-11e4-826e-74d235137cbd.png)

**Comment by erochest** [comment]
Can you post a screenshot of one of those items? Also, has your theme overridden the way that items are displayed?

**Comment by lydiatsai** [comment]
I was just using the pre-packaged "Rhythm" theme and just now I tested it with the default "Thanks, Roy" theme and the thumbnails still aren't appearing.

Here is a screenshot of the item page for the first item in the results list.

![seneca omeka evening dress](https://cloud.githubusercontent.com/assets/3915858/6129317/8dac9ea2-b10b-11e4-8425-66dfad74b06b.png)

**Comment by erochest** [comment]
I'm curious about the controls at the bottom of the image. What kind of image is that? Could you send it to me so I could use it in my testing? Thanks.

**Comment by lydiatsai** [comment]
It is actually an external HTML page embedded using iframes that we put into a custom metadata field we labeled "Image." The controls allow us to cycle through a series of photos, creating a "360 degree" effect.

I believe the thumbnails are being pulled from the picture uploaded as a "File" at the bottom.

Do you think the HTML page is interfering? The files for it are on an institutional server requiring an employee password to open, so I might have difficulty sending the files.

**Comment by anuragji** [comment]
For some projects I did end up modifying the `SolrSearch/views/shared/results/index.php` page to always display a thumbnail. The basic code looks like this:

     <?php
     // get item by ID
     $item = get_record_by_id('item', $doc->modelid);

     if(isset($item)) {
          
          // get associated files for this item
          $itemFiles = $item->Files;

          // display thumbnail for first associated image (if any)
          if(count($itemFiles) > 0) { ?>

                <a href="<?php echo $url; ?>" class="result-title">
                <?php echo file_image('thumbnail', array('alt' => metadata($item, array('Dublin Core', 'Title')), 'height' => '80'), $itemFiles[0] ); ?>
                </a>

          <?php }

     } ?>
