### ISSUE TITLE
Solr results only displayed for logged in users

### ISSUE THREAD

**Issue by akbrod** [scholarslab/SolrSearch#118]
This occurred just recently and I am not sure how to troubleshoot it.  Solr results are only being displayed for logged in users, if the user is not logged in, "0" results are returned.

Edit:  We were using Omeka 2.2.2 with the 2.2.0 Solr plugin, reverting to the 2.1.1 version fixed this issue in our case.

**Comment by akbrod** [comment]
We replicated this behavior on a different server.  The 2.2.0 fixes a lot of performance and other issues we were having, but we can't use it because you have to be logged in the get search results.

**Comment by akbrod** [comment]
This pull request https://github.com/scholarslab/SolrSearch/pull/117 and re-indexing fixes the above issue.

**Comment by erochest** [comment]
Great. I'm getting ready to merge that pull request and release it, so I'll go ahead and close this.
