### ISSUE TITLE
Special Character Handling

### ISSUE THREAD

**Issue by anuragji** [scholarslab/SolrSearch#119]
When I search for a some special characters for example `~, [, \:` I encounter a rather ungraceful `Apache_Solr_HttpTransportException '400' Status: Bad Request` error. 

Specific to the app, or more related to my setup? 

I am using the 2.1.1. version of the plugin, my Solr server is 4.10.2. 

If it is specific to the app, It would be nice to create a more graceful error message.

**Comment by erochest** [comment]
I would guess that it's specific to the app. Whichever, you *should* get a better error message. Thanks for the report.
