### ISSUE TITLE
Dublin Core Extended Set

### ISSUE THREAD

**Issue by anuragji** [scholarslab/SolrSearch#120]
We installed the Dublin Core Extended Set plugin, however, those elements do not appear as fields in the admin panel.

On first look, this could be more on the Omeka side. The `groupByElementSet()` function in _SolrSearch/models/SolrSearchFieldTable.php_ which returns the Element Sets, does not contain the extended DC items. However, when I go to Settings > Element Sets > Dublin Core in the Omeka admin, all of the extended items are listed along with the core items.

**Comment by erochest** [comment]
I'll dig into this. Thanks.

Just guessing, SolrSearch generates the list of elements when it's installed. I may need to add a button on the configuration page that allows it to be updated.

**Comment by anuragji** [comment]
That would make sense. Or perhaps there is hook which could be utilized whenever the Element Sets get updated.

**Comment by anuragji** [comment]
Yes, the available fields to get set during install. When I un- and subsequently reinstall the plugin, the fields of the extended set become available. I am not sure what would happen if one of the element set items gets removed - this too might cause an issue.

_Item Type_ elements get added correctly to the list of available fields.

**Comment by erochest** [comment]
Thanks for experimenting with that. I should be able to get a chance to look at it fairly soon.
