### ISSUE TITLE
Solr connection invalid

### ISSUE THREAD

**Issue by alanshortis** [scholarslab/SolrSearch#125]
Hello.

I am running Omeka on a vagrant box which includes solr. If I visit `http://{myhost}:8984/#/` I can see the Solr admin pages, and I can see java running if I use `ps aux` on the vagrant box itself.

However, entering this port number into the Server Configuration for the plugin in omeka doesn't appear to do it. I get 'Solr connection invalid' on this screen and attempting to search on the public site or updating an item gives me an error `Apache_Solr_HttpTransportException '404' Status: Not Found`.

What am I missing?

**Comment by alanshortis** [comment]
Sorry - human error. I didn't have the omeka solr core in the right place.

**Comment by erochest** [comment]
Glad you got this cleared. I suspected that might be the issue, but I hadn't gotten a VM set up with SolrSearch yet to test it out.
