### ISSUE TITLE
"Reindexing started" but nothing happens / no errors

### ISSUE THREAD

**Issue by iwemuiser** [scholarslab/SolrSearch#97]
I'm having trouble with the newest version of this plugin. I installed the plugin in the omeka plugins directory, installed Tomcat, am running a SolR(4.7.1) instance in Tomcat (7.0.28). I copied the "omeka" map from the plugin/solr-core directory in with the "collection1" example of solr. I then activated the omeka with the "Core Admin" in http://localhost:8080/solr/#/. It seems to be running fine. Also the plugin reports in green: "Solr connection is valid.".
When I press "Clear and reindex" it gives a green "Reindexing started.". Yet no index is built, and no error is given in the logs. Any idea what is going on here? It's happening on my macbook as well as our production server's test environment, so I suppose I'm doing something fundamentally wrong.
Thanks in advance!

**Comment by gnosisgithub** [comment]
Hi David,

Struggling with the same issue of the index quitting 1/3 of the way into the collection. Here is a thread I put up on Omeka Forums:   [https://forum.omeka.org/t/solr-indexing-timeout/3832/9](https://forum.omeka.org/t/solr-indexing-timeout/3832/9   )

What do you suggest next?

**Comment by davidmcclure** [comment]
Hey @gnosisgithub,

As `kloor` mentioned on the forum thread, this is probably because the "long running" dispatcher is set to the synchronous class, which means that indexing will run inside of the web request, which will generally have a fairly short timeout. What happens when you set it back?

```ini
jobs.dispatcher.longRunning = "Omeka_Job_Dispatcher_Adapter_BackgroundProcess"
```

**Comment by gnosisgithub** [comment]
I originally changed it to:
> Omeka_Job_Dispatcher_Adapter_Synchronous
because the Solr Index would not populate.
When I change it back to:
> Omeka_Job_Dispatcher_Adapter_BackgroundProcess
the index does not purge and re-index when going to Omeka=>Solr Search =>Index=> Clear and Reindex

**Comment by gnosisgithub** [comment]
We have determined that the script does not over-ride the php.ini settings, so timesout after 30 seconds. We do not want to change PHP settings because it presents an array of other issues and presents vulnerabilities to the server as a whole. Suggestions?

**Comment by gnosisgithub** [comment]
Plugin does not overwrite PHP.INI, so we temporarily open up max_execution limit in PHP to run and all works.

**Comment by gnosisgithub** [comment]
Another question, we have 2K items in one facet (subjects), so if we make visible the page would be cumbersome. Any idea how I could make a specific facet into a dropdown?  Wondering if there is something that can be done with the:  omeka//plugins/SolrSearch/views/shared/results/index.php file to turn just one facet, not all fields, into a dropdown.
